### ISSUE TITLE
Getting - undefined method `advance' for #<Date: 2016-02-29 ((2457448j,0s,0n),+0s,2299161j)> (NoMethodError)

### ISSUE THREAD

**Issue by snicko** [lewg/pingdom-to-graphite#17]
This appears to be different than #12 and #13  - 

I'm getting this on a couple of different systems running 2.3.0 and 2.0 - both using Active Support 3.2.22.1 - Any clues what I could be doing wrong here?

/home/centos/.gem/ruby/gems/activesupport-3.2.22.1/lib/active_support/core_ext/time/calculations.rb:118:in `advance': undefined method`advance' for #<Date: 2016-02-29 ((2457448j,0s,0n),+0s,2299161j)> (NoMethodError)
    from /home/centos/.gem/ruby/gems/activesupport-3.2.22.1/lib/active_support/duration.rb:96:in `block in sum'
    from /home/centos/.gem/ruby/gems/activesupport-3.2.22.1/lib/active_support/duration.rb:91:in`each'
    from /home/centos/.gem/ruby/gems/activesupport-3.2.22.1/lib/active_support/duration.rb:91:in `inject'
    from /home/centos/.gem/ruby/gems/activesupport-3.2.22.1/lib/active_support/duration.rb:91:in`sum'
    from /home/centos/.gem/ruby/gems/activesupport-3.2.22.1/lib/active_support/duration.rb:70:in `ago'
    from /home/centos/.gem/ruby/gems/pingdom-to-graphite-0.1.0/lib/pingdom-to-graphite/cli.rb:183:in`backfill'
    from /home/centos/.gem/ruby/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
    from /home/centos/.gem/ruby/gems/thor-0.19.1/lib/thor/invocation.rb:126:in`invoke_command'
    from /home/centos/.gem/ruby/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
    from /home/centos/.gem/ruby/gems/thor-0.19.1/lib/thor/base.rb:440:in`start'
    from /home/centos/.gem/ruby/gems/pingdom-to-graphite-0.1.0/bin/pingdom-to-graphite:10:in `<top (required)>'
    from /home/centos/bin/pingdom-to-graphite:23:in`load'
    from /home/centos/bin/pingdom-to-graphite:23:in `<main>'

**Comment by TryTryAgain** [comment]
Getting same thing, on Ubuntu:
/usr/local/rvm/gems/ruby-2.3.0/gems/activesupport-3.2.22.5/lib/active_support/core_ext/time/calculations.rb:118:in `advance': undefined method`advance' for #<Date: 2016-10-11 ((2457673j,0s,0n),+0s,2299161j)> (NoMethodError)
        from /usr/local/rvm/gems/ruby-2.3.0/gems/activesupport-3.2.22.5/lib/active_support/duration.rb:96:in `block in sum'
        from /usr/local/rvm/gems/ruby-2.3.0/gems/activesupport-3.2.22.5/lib/active_support/duration.rb:91:in`each'
        from /usr/local/rvm/gems/ruby-2.3.0/gems/activesupport-3.2.22.5/lib/active_support/duration.rb:91:in `inject'
        from /usr/local/rvm/gems/ruby-2.3.0/gems/activesupport-3.2.22.5/lib/active_support/duration.rb:91:in`sum'
        from /usr/local/rvm/gems/ruby-2.3.0/gems/activesupport-3.2.22.5/lib/active_support/duration.rb:70:in `ago'
        from /root/GitRepos/pingdom-to-graphite/lib/pingdom-to-graphite/cli.rb:183:in`backfill'
        from /usr/local/rvm/gems/ruby-2.3.0/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
        from /usr/local/rvm/gems/ruby-2.3.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in`invoke_command'
        from /usr/local/rvm/gems/ruby-2.3.0/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
        from /usr/local/rvm/gems/ruby-2.3.0/gems/thor-0.19.1/lib/thor/base.rb:440:in`start'
        from ./pingdom-to-graphite:10:in `<main>'
